# Generated by Django 4.0 on 2022-01-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211125_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-update', '-create']},
        ),
    ]
